global:
  clusterName: ${k8s_cluster_name}  

serviceAccount:
  create: true
  name: ${service_account_name}
  annotations:
    eks.amazonaws.com/role-arn: ${kubecost_iam_role_arn}  

# CORRECTED STRUCTURE BELOW
kubecostProductConfigs:
  # Cluster configuration
  clusterName: ${k8s_cluster_name} 
  
  # Cost model configuration
  model:
    enabled: true
    awsAthenaProjectID: ${aws_account_id}
    awsRegion: ${aws_region}
  
  # Network costs
  networkCosts:
    enabled: true

  # Cloud integration
  cloudIntegrationSecret: ""  # Use this instead of inline credentials

# Prometheus configuration (TOP-LEVEL KEY)
prometheus:
  enabled: true
  server:
    persistentVolume:
      enabled: true
      storageClass: ${storage_class}
      size: ${storage_size}
      accessModes: ["ReadWriteMany"]

# Service configuration (TOP-LEVEL KEY)
service:
  type: ClusterIP
  annotations: {}

# Resource configuration (PER-COMPONENT)
kubecostFrontend:
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 2Gi

kubecostCostModel:
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 2Gi
  # ETL settings belong HERE
  extraEnv:
    - name: METRIC_RESOLUTION
      value: "1m"
    - name: ETL_DAILY_STORE_DURATION_DAYS
      value: "30"
    - name: ETL_HOURLY_STORE_DURATION_HOURS
      value: "720"

# ServiceMonitor (TOP-LEVEL KEY)
serviceMonitor:
  enabled: true
  interval: 30s
  additionalLabels:
    release: "kube-prometheus"

grafana:
  enabled: true
  #adminPassword: "securepassword"  # Change this!
    
  # Add persistent storage
  persistence:
    enabled: true
    storageClassName: ${storage_class}
    size: ${storage_size}
    accessModes: ["ReadWriteMany"]
    
  # Add Ingress
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-${environment}
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      nginx.ingress.kubernetes.io/backend-protocol: HTTP
      external-dns.alpha.kubernetes.io/hostname: ${ingress_host}
      nginx.ingress.kubernetes.io/rewrite-target: /  
    hosts:
      - ${ingress_host}
    path: /
    pathType: Prefix
    tls:
      - hosts:
          - ${ingress_host}
        secretName: ${ingress_host}-tls
