deploymentMode: "Distributed"

singleBinary:
  enabled: false

serviceAccount:
  create: true
  name: "loki-sa"   #${loki_service_account_name}
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::717949064245:role/eks-managed-clstr-dev-loki-role"  # ${loki_role_arn}

serviceMonitor:
  enabled: true
  additionalLabels:
    release: "kube-prometheus-stack"

loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  
  schemaConfig:
    configs:
      - from: "2020-10-24"
        store: "boltdb-shipper"
        object_store: "aws"
        schema: "v11"
        index:
          prefix: "loki_index_"
          period: "24h"
      - from: "2025-07-24"
        store: "tsdb"
        object_store: "aws"
        schema: "v13"
        index:
          prefix: "loki_index_"
          period: "24h"
  
  storageConfig:
    tsdb_shipper:
      active_index_directory: /var/loki/tsdb-index
      shared_store: aws
    aws:
      s3: s3://my-loki-bucket
      region: eu-west-1
      s3forcepathstyle: true

  
  storage:
    bucketNames:
      chunks:  "loki-storage-0b1303af"  #"${s3_bucket_name}"
      ruler: "loki-storage-0b1303af"
      admin: "loki-storage-0b1303af"

distributor:
  replicas: 2
  maxUnavailable: 1

ingester:
  replicas: 2
  persistence:
    enabled: true
    size: "10Gi"
    storageClass: "ebs-gp3-sc" #"${ebs_storage_class_name}"

querier:
  replicas: 2
  maxUnavailable: 1

queryFrontend:
  replicas: 2
  maxUnavailable: 1

compactor:
  enabled: true
  retention_enabled: true
  retention_delete_delay: "2h"
  retention_delete_worker_count: 150
  working_directory: "/var/loki/compactor"
  shared_store: "aws"

ruler:
  enabled: true
  replicas: 1
  directories:
    rules: "/etc/loki/rules"

gateway:
  enabled: true

queryScheduler:
  enabled: true

frontendWorker:
  enabled: true

backend:
  enabled: false
  replicas: 0

read:
  enabled: false
  replicas: 0

write:
  enabled: false
  replicas: 0
