deploymentMode: "Distributed"

singleBinary:
  enabled: false

serviceAccount:
  create: true
  name: ${loki_service_account_name}
  annotations:
    eks.amazonaws.com/role-arn: ${loki_role_arn}

serviceMonitor:
  enabled: true
  additionalLabels:
    release: "kube-prometheus-stack"

loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  
  schemaConfig:
    configs:
      - from: "2020-10-24"
        store: "boltdb-shipper"
        object_store: "aws"
        schema: "v11"
        index:
          prefix: "loki_index_"
          period: "24h"
  
  storageConfig:
    aws:
      s3: "s3://${s3_bucket_name}"
      region: "${aws_region}"
      s3forcepathstyle: true
    boltdb_shipper:
      active_index_directory: "/var/loki/index"
      cache_location: "/var/loki/cache"
      cache_ttl: "24h"
      shared_store: "aws"
  
  storage:
    bucketNames:
      chunks: "${s3_bucket_name}"
      ruler: "${s3_bucket_name}"
      admin: "${s3_bucket_name}"

distributor:
  replicas: 2
  maxUnavailable: 1

ingester:
  replicas: 2
  persistence:
    enabled: true
    size: "10Gi"
    storageClass: "${ebs_storage_class_name}"

querier:
  replicas: 2
  maxUnavailable: 1

queryFrontend:
  replicas: 2
  maxUnavailable: 1

compactor:
  enabled: true
  retention_enabled: true
  retention_delete_delay: "2h"
  retention_delete_worker_count: 150
  working_directory: "/var/loki/compactor"
  shared_store: "aws"

ruler:
  enabled: true
  replicas: 1
  directories:
    rules: "/etc/loki/rules"

gateway:
  enabled: true

queryScheduler:
  enabled: true

frontendWorker:
  enabled: true

backend:
  enabled: false
  replicas: 0

read:
  enabled: false
  replicas: 0

write:
  enabled: false
  replicas: 0
