deploymentMode: "Distributed"

singleBinary:
  enabled: false

serviceAccount:
  create: true
  name: "loki-sa"
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::717949064245:role/eks-managed-clstr-dev-loki-role"

serviceMonitor:
  enabled: true
  additionalLabels:
    release: "kube-prometheus-stack"

loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  
  config: |
    limits_config:
      allow_structured_metadata: false
  
  schemaConfig:
    configs:
      - from: "2020-10-24"
        store: "boltdb-shipper"
        object_store: "aws"
        schema: "v11"
        index:
          prefix: "loki_index_"
          period: "24h"
  
  storageConfig:  # Changed from storageConfig to storage_config
    aws:
      s3: "s3://loki-storage-0b1303af"
      region: "eu-west-2"
      s3forcepathstyle: true
    boltdb_shipper:
      active_index_directory: "/var/loki/index"
      cache_location: "/var/loki/cache"
      cache_ttl: "24h"
      shared_store: "aws"

# Distributed components (top level)
distributor:
  replicas: 2
  maxUnavailable: 1

ingester:
  replicas: 2
  persistence:
    enabled: true
    size: "10Gi"
    storageClass: "ebs-gp3-sc"

querier:
  replicas: 2
  maxUnavailable: 1

queryFrontend:
  replicas: 2
  maxUnavailable: 1

compactor:
  enabled: true
  retention_enabled: true
  retention_delete_delay: "2h"
  retention_delete_worker_count: 150
  working_directory: "/var/loki/compactor"
  shared_store: "aws"

ruler:
  enabled: true
  replicas: 1
  directories:
    rules: "/etc/loki/rules"

gateway:
  enabled: true

queryScheduler:
  enabled: true

frontendWorker:
  enabled: true

backend:
  enabled: false
  replicas: 0

read:
  enabled: false
  replicas: 0

write:
  enabled: false
  replicas: 0
