apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod-example
  labels:
    app: gpu-test
spec:
  # Node selection criteria
  nodeSelector:
    accelerator: nvidia  # Requires nodes with this label
    instance-type: gpu
    # kubernetes.io/arch: amd64  # Optional: Architecture selector
    # node-type: gpu-optimized  # Additional custom label


  containers:
  - name: cuda-container
    image: nvidia/cuda:12.2.0-base-ubuntu22.04
    command: ["/bin/bash", "-c", "--"]
    args: ["while true; do sleep 30; done;"]
    resources:
      limits:
        nvidia.com/gpu: 1  # Request 1 GPU
    securityContext:
      capabilities:
        add: ["SYS_ADMIN"]  # Often needed for GPU workloads

  # Optional: Tolerations for tainted nodes
  tolerations:
  - key: "nvidia.com/gpu"
    operator: "Exists"
    effect: "NoSchedule"
